//ACTION TYPES FOR AUTHENTICATION REDUCER
export const LOGIN = 'LOGIN';
export const LOG_OUT = 'LOG_OUT';
export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';
export const AUTH_ERROR = 'AUTH_ERROR';
export const RESET_ERROR = 'RESET_ERROR';
//ACTION TYPES FOR ROUTINES REDUCER
export const SAVE_ROUTINE = 'SAVE_ROUTINE';

